### PR TITLE
Solved Maximize Walk Value (DEMTREE),

### PR DESCRIPTION
**Pull request by Error404m**

### CODE REVIEW

**Comment by aryamasinha** [comment]
Could you work on one issue first and wait for your PR to be merged?

**Comment by aryamasinha** [comment]
Here , i see you have worked on 2 issues

**Comment by Error404m** [comment]
@aryamasinha , Solved both issues & sent pull request also pl. #86 
Screenshot from 2020-10-17 18-32-22

**Comment by aryamasinha** [comment]
No , i mean could you please delete any one file and keep only singe file per PR?

**Comment by aryamasinha** [comment]
Add the other file in the next PR

**Pull request closed without merging**
